/*
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.models.V1beta1IDRange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
 */
@ApiModel(description = "SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.")

public class V1beta1SupplementalGroupsStrategyOptions {
  @SerializedName("ranges")
  private List<V1beta1IDRange> ranges = new ArrayList<V1beta1IDRange>();

  @SerializedName("rule")
  private String rule = null;

  public V1beta1SupplementalGroupsStrategyOptions ranges(List<V1beta1IDRange> ranges) {
    this.ranges = ranges;
    return this;
  }

  public V1beta1SupplementalGroupsStrategyOptions addRangesItem(V1beta1IDRange rangesItem) {
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * Ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end.
   * @return ranges
  **/
  @ApiModelProperty(example = "null", value = "Ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end.")
  public List<V1beta1IDRange> getRanges() {
    return ranges;
  }

  public void setRanges(List<V1beta1IDRange> ranges) {
    this.ranges = ranges;
  }

  public V1beta1SupplementalGroupsStrategyOptions rule(String rule) {
    this.rule = rule;
    return this;
  }

   /**
   * Rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
   * @return rule
  **/
  @ApiModelProperty(example = "null", value = "Rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.")
  public String getRule() {
    return rule;
  }

  public void setRule(String rule) {
    this.rule = rule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SupplementalGroupsStrategyOptions v1beta1SupplementalGroupsStrategyOptions = (V1beta1SupplementalGroupsStrategyOptions) o;
    return Objects.equals(this.ranges, v1beta1SupplementalGroupsStrategyOptions.ranges) &&
        Objects.equals(this.rule, v1beta1SupplementalGroupsStrategyOptions.rule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranges, rule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SupplementalGroupsStrategyOptions {\n");
    
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

