/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.NetworkingV1beta1HTTPIngressPath;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkingV1beta1HTTPIngressRuleValue
 */
public class NetworkingV1beta1HTTPIngressRuleValueTest {
    private final NetworkingV1beta1HTTPIngressRuleValue model = new NetworkingV1beta1HTTPIngressRuleValue();

    /**
     * Model tests for NetworkingV1beta1HTTPIngressRuleValue
     */
    @Test
    public void testNetworkingV1beta1HTTPIngressRuleValue() {
        // TODO: test NetworkingV1beta1HTTPIngressRuleValue
    }

    /**
     * Test the property 'paths'
     */
    @Test
    public void pathsTest() {
        // TODO: test paths
    }

}
