/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.models.V1LabelSelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V2beta1ExternalMetricStatus
 */
public class V2beta1ExternalMetricStatusTest {
    private final V2beta1ExternalMetricStatus model = new V2beta1ExternalMetricStatus();

    /**
     * Model tests for V2beta1ExternalMetricStatus
     */
    @Test
    public void testV2beta1ExternalMetricStatus() {
        // TODO: test V2beta1ExternalMetricStatus
    }

    /**
     * Test the property 'currentAverageValue'
     */
    @Test
    public void currentAverageValueTest() {
        // TODO: test currentAverageValue
    }

    /**
     * Test the property 'currentValue'
     */
    @Test
    public void currentValueTest() {
        // TODO: test currentValue
    }

    /**
     * Test the property 'metricName'
     */
    @Test
    public void metricNameTest() {
        // TODO: test metricName
    }

    /**
     * Test the property 'metricSelector'
     */
    @Test
    public void metricSelectorTest() {
        // TODO: test metricSelector
    }

}
