/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.coreos.monitoring.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.kubernetes.client.openapi.JSON;

/**
 * V1PrometheusStatusShardStatusesInner
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-01T07:02:10.169254Z[Etc/UTC]")
public class V1PrometheusStatusShardStatusesInner {
  public static final String SERIALIZED_NAME_AVAILABLE_REPLICAS = "availableReplicas";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_REPLICAS)
  private Integer availableReplicas;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_SHARD_I_D = "shardID";
  @SerializedName(SERIALIZED_NAME_SHARD_I_D)
  private String shardID;

  public static final String SERIALIZED_NAME_UNAVAILABLE_REPLICAS = "unavailableReplicas";
  @SerializedName(SERIALIZED_NAME_UNAVAILABLE_REPLICAS)
  private Integer unavailableReplicas;

  public static final String SERIALIZED_NAME_UPDATED_REPLICAS = "updatedReplicas";
  @SerializedName(SERIALIZED_NAME_UPDATED_REPLICAS)
  private Integer updatedReplicas;

  public V1PrometheusStatusShardStatusesInner() {
  }

  public V1PrometheusStatusShardStatusesInner availableReplicas(Integer availableReplicas) {
    
    this.availableReplicas = availableReplicas;
    return this;
  }

   /**
   * Total number of available pods (ready for at least minReadySeconds) targeted by this shard.
   * @return availableReplicas
  **/
  @jakarta.annotation.Nonnull
  public Integer getAvailableReplicas() {
    return availableReplicas;
  }


  public void setAvailableReplicas(Integer availableReplicas) {
    this.availableReplicas = availableReplicas;
  }


  public V1PrometheusStatusShardStatusesInner replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Total number of pods targeted by this shard.
   * @return replicas
  **/
  @jakarta.annotation.Nonnull
  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public V1PrometheusStatusShardStatusesInner shardID(String shardID) {
    
    this.shardID = shardID;
    return this;
  }

   /**
   * Identifier of the shard.
   * @return shardID
  **/
  @jakarta.annotation.Nonnull
  public String getShardID() {
    return shardID;
  }


  public void setShardID(String shardID) {
    this.shardID = shardID;
  }


  public V1PrometheusStatusShardStatusesInner unavailableReplicas(Integer unavailableReplicas) {
    
    this.unavailableReplicas = unavailableReplicas;
    return this;
  }

   /**
   * Total number of unavailable pods targeted by this shard.
   * @return unavailableReplicas
  **/
  @jakarta.annotation.Nonnull
  public Integer getUnavailableReplicas() {
    return unavailableReplicas;
  }


  public void setUnavailableReplicas(Integer unavailableReplicas) {
    this.unavailableReplicas = unavailableReplicas;
  }


  public V1PrometheusStatusShardStatusesInner updatedReplicas(Integer updatedReplicas) {
    
    this.updatedReplicas = updatedReplicas;
    return this;
  }

   /**
   * Total number of non-terminated pods targeted by this shard that have the desired spec.
   * @return updatedReplicas
  **/
  @jakarta.annotation.Nonnull
  public Integer getUpdatedReplicas() {
    return updatedReplicas;
  }


  public void setUpdatedReplicas(Integer updatedReplicas) {
    this.updatedReplicas = updatedReplicas;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1PrometheusStatusShardStatusesInner v1PrometheusStatusShardStatusesInner = (V1PrometheusStatusShardStatusesInner) o;
    return Objects.equals(this.availableReplicas, v1PrometheusStatusShardStatusesInner.availableReplicas) &&
        Objects.equals(this.replicas, v1PrometheusStatusShardStatusesInner.replicas) &&
        Objects.equals(this.shardID, v1PrometheusStatusShardStatusesInner.shardID) &&
        Objects.equals(this.unavailableReplicas, v1PrometheusStatusShardStatusesInner.unavailableReplicas) &&
        Objects.equals(this.updatedReplicas, v1PrometheusStatusShardStatusesInner.updatedReplicas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableReplicas, replicas, shardID, unavailableReplicas, updatedReplicas);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1PrometheusStatusShardStatusesInner {\n");
    sb.append("    availableReplicas: ").append(toIndentedString(availableReplicas)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    shardID: ").append(toIndentedString(shardID)).append("\n");
    sb.append("    unavailableReplicas: ").append(toIndentedString(unavailableReplicas)).append("\n");
    sb.append("    updatedReplicas: ").append(toIndentedString(updatedReplicas)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("availableReplicas");
    openapiFields.add("replicas");
    openapiFields.add("shardID");
    openapiFields.add("unavailableReplicas");
    openapiFields.add("updatedReplicas");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("availableReplicas");
    openapiRequiredFields.add("replicas");
    openapiRequiredFields.add("shardID");
    openapiRequiredFields.add("unavailableReplicas");
    openapiRequiredFields.add("updatedReplicas");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to V1PrometheusStatusShardStatusesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!V1PrometheusStatusShardStatusesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in V1PrometheusStatusShardStatusesInner is not found in the empty JSON string", V1PrometheusStatusShardStatusesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!V1PrometheusStatusShardStatusesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `V1PrometheusStatusShardStatusesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V1PrometheusStatusShardStatusesInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("shardID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `shardID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shardID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V1PrometheusStatusShardStatusesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V1PrometheusStatusShardStatusesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V1PrometheusStatusShardStatusesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V1PrometheusStatusShardStatusesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<V1PrometheusStatusShardStatusesInner>() {
           @Override
           public void write(JsonWriter out, V1PrometheusStatusShardStatusesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V1PrometheusStatusShardStatusesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of V1PrometheusStatusShardStatusesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1PrometheusStatusShardStatusesInner
  * @throws IOException if the JSON string is invalid with respect to V1PrometheusStatusShardStatusesInner
  */
  public static V1PrometheusStatusShardStatusesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1PrometheusStatusShardStatusesInner.class);
  }

 /**
  * Convert an instance of V1PrometheusStatusShardStatusesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

