#!/usr/bin/env python3

from __future__ import annotations

import argparse
from dataclasses import dataclass
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


GENERATED_START = "# BEGIN: generated by scripts/sync_bazel_dependencies.py"
GENERATED_END = "# END: generated by scripts/sync_bazel_dependencies.py"
MAX_PROPERTY_RESOLUTION_DEPTH = 20
SECTION_CORE = "core"
SECTION_SPRING = "spring (Java 17+ modules)"
SECTION_TEST = "test"
SPRING_BOOT_GROUP = "org.springframework.boot"
SPRING_FRAMEWORK_GROUP = "org.springframework"
SPRING_BOOT_COORDINATE = "org.springframework.boot:spring-boot"
SPRING_CORE_COORDINATE = "org.springframework:spring-core"
EXCLUDED_BAZEL_COORDINATES = {
    "commons-cli:commons-cli",
    "com.google.code.findbugs:jsr305",
    "org.junit.jupiter:junit-jupiter",
}


@dataclass(frozen=True)
class ManagedDependency:
    group_id: str
    artifact_id: str
    version: str
    scope: str = ""

    @property
    def coordinate(self) -> str:
        return f"{self.group_id}:{self.artifact_id}"

    @property
    def bazel_artifact(self) -> str:
        return f"{self.coordinate}:{self.version}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync Bazel dependency declarations from the root pom.xml."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root containing pom.xml and MODULE.bazel.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if MODULE.bazel is not up to date.",
    )
    return parser.parse_args()


def local_name(tag: str) -> str:
    return tag.split("}", 1)[-1]


def parse_managed_dependencies(pom_path: Path) -> list[ManagedDependency]:
    root = ET.parse(pom_path).getroot()
    namespace = {}
    if root.tag.startswith("{"):
        namespace["m"] = root.tag[1:].split("}", 1)[0]
        prefix = "m:"
    else:
        prefix = ""

    properties_element = root.find(f"{prefix}properties", namespace)
    properties = {}
    if properties_element is not None:
        for child in properties_element:
            properties[local_name(child.tag)] = (child.text or "").strip()

    project_version = (root.findtext(f"{prefix}version", default="", namespaces=namespace) or "").strip()
    if project_version:
        properties.setdefault("project.version", project_version)
        properties.setdefault("pom.version", project_version)
        properties.setdefault("version", project_version)

    def resolve(value: str) -> str:
        resolved = value
        for _ in range(MAX_PROPERTY_RESOLUTION_DEPTH):
            updated = re.sub(
                r"\$\{([^}]+)\}",
                lambda match: properties.get(match.group(1), match.group(0)),
                resolved,
            )
            if updated == resolved:
                return updated
            resolved = updated
        raise ValueError(f"Could not fully resolve property expression: {value}")

    managed_dependencies = []
    dependency_path = f"{prefix}dependencyManagement/{prefix}dependencies/{prefix}dependency"
    for dependency in root.findall(dependency_path, namespace):
        group_id = dependency.findtext(f"{prefix}groupId", default="", namespaces=namespace).strip()
        artifact_id = dependency.findtext(
            f"{prefix}artifactId", default="", namespaces=namespace
        ).strip()
        version = dependency.findtext(f"{prefix}version", default="", namespaces=namespace).strip()
        scope = dependency.findtext(f"{prefix}scope", default="", namespaces=namespace).strip()
        if group_id and artifact_id and version:
            managed_dependencies.append(
                ManagedDependency(
                    group_id=group_id,
                    artifact_id=artifact_id,
                    version=resolve(version),
                    scope=scope,
                )
            )
    return managed_dependencies


def classify_dependency(dependency: ManagedDependency) -> str:
    if dependency.group_id == SPRING_FRAMEWORK_GROUP:
        return SECTION_SPRING
    if dependency.scope == "test":
        return SECTION_TEST
    return SECTION_CORE


def partition_dependencies(
    managed_dependencies: list[ManagedDependency],
) -> tuple[dict[str, list[ManagedDependency]], list[ManagedDependency]]:
    install_sections = {
        SECTION_CORE: [],
        SECTION_SPRING: [],
        SECTION_TEST: [],
    }
    spring_boot_dependencies = []

    for dependency in managed_dependencies:
        if dependency.group_id == SPRING_BOOT_GROUP:
            spring_boot_dependencies.append(dependency)
            continue
        if dependency.coordinate in EXCLUDED_BAZEL_COORDINATES:
            continue
        install_sections[classify_dependency(dependency)].append(dependency)

    if not spring_boot_dependencies:
        raise ValueError("No org.springframework.boot dependencies found in dependencyManagement.")

    return install_sections, spring_boot_dependencies


def find_dependency(
    dependencies: list[ManagedDependency], coordinate: str
) -> ManagedDependency:
    for dependency in dependencies:
        if dependency.coordinate == coordinate:
            return dependency
    raise ValueError(f"Missing expected dependencyManagement entry: {coordinate}")


def render_generated_block(managed_dependencies: list[ManagedDependency]) -> str:
    install_sections, spring_boot_dependencies = partition_dependencies(managed_dependencies)
    spring_framework_exclusions = [dependency.coordinate for dependency in install_sections[SECTION_SPRING]]
    if not spring_framework_exclusions:
        raise ValueError("No spring-framework exclusions found for spring boot artifacts.")

    lines = [
        GENERATED_START,
        "# Generated from pom.xml by scripts/sync_bazel_dependencies.py.",
        "# Do not edit this block by hand; update pom.xml and rerun the script instead.",
        "maven.install(",
        "    artifacts = [",
    ]
    for section, dependencies in install_sections.items():
        lines.append(f"        # ---- {section} ----")
        for dependency in dependencies:
            lines.append(f'        "{dependency.bazel_artifact}",')
    spring_boot_version = find_dependency(
        spring_boot_dependencies, SPRING_BOOT_COORDINATE
    ).version
    spring_framework_version = find_dependency(
        install_sections[SECTION_SPRING], SPRING_CORE_COORDINATE
    ).version
    lines.extend(
        [
            "    ],",
            "    repositories = [",
            '        "https://repo1.maven.org/maven2",',
            '        "https://repo.spring.io/milestone",',
            "    ],",
            "    fetch_sources = False,",
            '    lock_file = "//:maven_install.json",',
            ")",
            "",
            f"# Spring Boot {spring_boot_version} artifacts declared with exclusions to keep",
            f"# spring-framework pinned to {spring_framework_version}.",
            "_SPRING_FRAMEWORK_EXCLUSIONS = [",
        ]
    )
    for exclusion in spring_framework_exclusions:
        lines.append(f'    "{exclusion}",')
    lines.extend(["]", ""])

    for dependency in spring_boot_dependencies:
        lines.extend(
            [
                "maven.artifact(",
                f'    artifact = "{dependency.artifact_id}",',
                '    group = "org.springframework.boot",',
                f'    version = "{dependency.version}",',
                "    exclusions = _SPRING_FRAMEWORK_EXCLUSIONS,",
                ")",
                "",
            ]
        )

    if len({dependency.version for dependency in spring_boot_dependencies}) != 1:
        raise ValueError("Spring Boot artifact versions diverged in dependencyManagement.")

    lines.append(GENERATED_END)
    return "\n".join(lines) + "\n"


def sync_module(module_path: Path, generated_block: str, check_only: bool) -> bool:
    module_text = module_path.read_text()
    pattern = re.compile(
        rf"{re.escape(GENERATED_START)}\n.*?{re.escape(GENERATED_END)}\n?",
        re.DOTALL,
    )
    match = pattern.search(module_text)
    if not match:
        raise ValueError(
            f"Could not find generated block markers in {module_path}. "
            f"Expected {GENERATED_START!r} and {GENERATED_END!r}."
        )

    updated_text = module_text[: match.start()] + generated_block + module_text[match.end() :]
    changed = updated_text != module_text
    if changed and not check_only:
        module_path.write_text(updated_text)
    return changed


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    pom_path = root / "pom.xml"
    module_path = root / "MODULE.bazel"

    managed_dependencies = parse_managed_dependencies(pom_path)
    generated_block = render_generated_block(managed_dependencies)
    changed = sync_module(module_path, generated_block, args.check)

    if args.check and changed:
        print(f"{module_path} is out of date. Run {Path(__file__).name} to regenerate it.")
        return 1

    if not args.check and changed:
        print(f"Updated {module_path}")
    elif not args.check:
        print(f"{module_path} is already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
