/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.openapi.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.PolicyV1beta1IDRange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PolicyV1beta1FSGroupStrategyOptions
 */
public class PolicyV1beta1FSGroupStrategyOptionsTest {
    private final PolicyV1beta1FSGroupStrategyOptions model = new PolicyV1beta1FSGroupStrategyOptions();

    /**
     * Model tests for PolicyV1beta1FSGroupStrategyOptions
     */
    @Test
    public void testPolicyV1beta1FSGroupStrategyOptions() {
        // TODO: test PolicyV1beta1FSGroupStrategyOptions
    }

    /**
     * Test the property 'ranges'
     */
    @Test
    public void rangesTest() {
        // TODO: test ranges
    }

    /**
     * Test the property 'rule'
     */
    @Test
    public void ruleTest() {
        // TODO: test rule
    }

}
