/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.15.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.openapi.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1GroupVersionForDiscovery
 */
public class V1GroupVersionForDiscoveryTest {
    private final V1GroupVersionForDiscovery model = new V1GroupVersionForDiscovery();

    /**
     * Model tests for V1GroupVersionForDiscovery
     */
    @Test
    public void testV1GroupVersionForDiscovery() {
        // TODO: test V1GroupVersionForDiscovery
    }

    /**
     * Test the property 'groupVersion'
     */
    @Test
    public void groupVersionTest() {
        // TODO: test groupVersion
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
