name: build

on:
  push:
    branches: [ "master", "release-**" ]
    paths:
      - "**/*.java"
      - "**/pom.xml"
      - "pom.xml"
      - ".github/workflows/maven.yml"
  pull_request:
    branches: [ "master", "release-**" ]
    paths:
      - "**/*.java"
      - "**/pom.xml"
      - "pom.xml"
      - ".github/workflows/maven.yml"

jobs:
  build:
    name: Java 17 Maven Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.m2/repository/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: ./mvnw -q -B clean test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
