name: Upload Snapshot

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  verify:
    name: latest-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: 17.0.x
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Assert Snapshot Version
        run: |
          ./mvnw clean install -Dmaven.test.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          ./mvnw -q \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Dexec.executable=echo \
            -Dexec.args='${project.version}' \
            exec:exec | perl -ne 'die unless m/.*-SNAPSHOT/'
      - name: Publish to Apache Maven Central
        run: ./mvnw deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.SNAPSHOT_UPLOAD_USER }}
          CENTRAL_TOKEN: ${{ secrets.SNAPSHOT_UPLOAD_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
